language: python
python:
      - "3.6"
install:
      - pip install -r requirements.txt
script:
          - screen -S test -d -m python image_processor_web_server.py
          - pytest -v --cov --pep8